package com.android.cleanarchitectureproject.presentation.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Immutable
data class AppDimensions(
    val pointTwoSp: TextUnit = 0.2.sp,
    val pointThreeSp: TextUnit = 0.3.sp,
    val pointFourSp: TextUnit = 0.4.sp,
    val pointEightSp: TextUnit = 0.8.sp,
    val onePointTwoSp: TextUnit = 1.2.sp,
    val onePointFourSp: TextUnit = 1.4.sp,
    val onePointEightSp: TextUnit = 1.8.sp,
    val zeroSp: TextUnit = 0.sp,
    val nineSp: TextUnit = 9.sp,
    val tenSp: TextUnit = 10.sp,
    val elevenSp: TextUnit = 11.sp,
    val twelveSp: TextUnit = 12.sp,
    val thirteenSp: TextUnit = 13.sp,
    val fourteenSp: TextUnit = 14.sp,
    val sixteenSp: TextUnit = 16.sp,
    val seventeenSp: TextUnit = 17.sp,
    val twentySp: TextUnit = 20.sp,
    val twentyFourSp: TextUnit = 24.sp,
    val zeroDp: Dp = 0.dp,
    val pointFiveDp: Dp = 0.5.dp,
    val oneDp: Dp = 1.dp,
    val twoDp: Dp = 2.dp,
    val threeDp: Dp = 3.dp,
    val fourDp: Dp = 4.dp,
    val fiveDp: Dp = 5.dp,
    val sevenDp: Dp = 7.dp,
    val eightDp: Dp = 8.dp,
    val tenDp: Dp = 10.dp,
    val twelveDp: Dp = 12.dp,
    val thirteenDp: Dp = 13.dp,
    val fifteenDp: Dp = 15.dp,
    val sixteenDp: Dp = 16.dp,
    val eighteenDp: Dp = 18.dp,
    val twentyDp: Dp = 20.dp,
    val twentyTwoDp: Dp = 22.dp,
    val twentyFourDp: Dp = 24.dp,
    val twentyEightDp: Dp = 28.dp,
    val thirtyTwoDp: Dp = 32.dp,
    val thirtyFourDp: Dp = 34.dp,
    val thirtySixDp: Dp = 36.dp,
    val thirtyEightDp: Dp = 38.dp,
    val fourtyDp: Dp = 40.dp,
    val fortyFourDp: Dp = 44.dp,
    val fourtyEightDp: Dp = 48.dp,
    val fortyNineDp: Dp = 49.dp,
    val fiftySixDp: Dp = 56.dp,
    val fiftyEightDp: Dp = 58.dp,
    val fiftyTwoDp: Dp = 52.dp,
    val fiftyFourDp: Dp = 54.dp,
    val sixtyDp: Dp = 60.dp,
    val seventyTwoDp: Dp = 72.dp,
    val sixtyFourDp: Dp = 64.dp,
    val seventyFourDp: Dp = 74.dp,
    val eightyDp: Dp = 80.dp,
    val eightyTwoDp: Dp = 82.dp,
    val eightyFourDp: Dp = 84.dp,
    val eightySixDp: Dp = 86.dp,
    val ninetySixDp: Dp = 96.dp,
    val ninetyEightDp: Dp = 98.dp,
    val oneHundredDp: Dp = 100.dp,
    val oneZeroFourDp: Dp = 104.dp,
    val oneTwentyThreeDp: Dp = 123.dp,
    val oneTwentyDp: Dp = 120.dp,
    val oneFortyFourDp: Dp = 144.dp,
    val oneFortyTwoDp: Dp = 142.dp,
    val oneSixtyFiveDp: Dp = 165.dp,
    val oneSeventyFour: Dp = 174.dp,
    val twoTwentySixDp: Dp = 226.dp,
    val twoThirtyOneDp: Dp = 231.dp,
    val twoHundredDp: Dp = 250.dp,
    val twoFiftyDp: Dp = 250.dp,
    val twoSixtyFiveDp: Dp = 265.dp,
    val twoNinetyDp: Dp = 290.dp,
    val oneF: Float = 1f
)

internal val AppCustomDimensions = staticCompositionLocalOf { AppDimensions() }
